// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkxvfuiwdwpjriddptfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdreHZmdWl3ZHdwanJpZGRwdGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDk1MjIsImV4cCI6MjA2ODUyNTUyMn0.5gcX0yvkW1oWSYgzbSbl0k1pBPFc29A0p29dhqLRDNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});